### ISSUE TITLE
Press book to crash ("Flaxbeard's Steam Power"'s ingame manual, library screen)

### ISSUE THREAD

**Issue by DanNetwalker** [joshiejack/Enchiridion#29]
Hi, I got this crash while accesing a mod's ingame manual by clicking on it at the "Library" enchiridion screen. 

"java.lang.NullPointerException: Updating screen events
        at flaxbeard.steamcraft.integration.EnchiridionIntegration.findBook(EnchiridionIntegration.java:43)
        at flaxbeard.steamcraft.gui.GuiSteamcraftBook.<init>(GuiSteamcraftBook.java:92)
        at flaxbeard.steamcraft.gui.SteamcraftGuiHandler.getClientGuiElement(SteamcraftGuiHandler.java:56)
        at cpw.mods.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:263)
        at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:93)
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209)
        at flaxbeard.steamcraft.item.ItemSteamcraftBook.func_77659_a(ItemSteamcraftBook.java:24)
        at joshie.enchiridion.library.handlers.DefaultBookHandler.handle(DefaultBookHandler.java:16)"

Any chance it may be fixed from your side of the fence, or should I tell the mod maker?
Here's the full details: http://pastebin.com/6x5CbRFA
Give me a yell should you need more info, happy to help :)

**Comment by joshiejack** [comment]
I wonder why it would be calling the ench1 integration? They have seperate mod ids. Try changing it's type to switch in the library books json, if that fails try changing it to network.

**Comment by joshiejack** [comment]
Any word @DanNetwalker

**Comment by DanNetwalker** [comment]
Sorry, trapped in real life. I'll try it and reach you back. 

In fact, I have both enchiridion and enchiridion 2 installed. Whould that be related?

**Comment by joshiejack** [comment]
Nah. They should both work fine together.
