### ISSUE TITLE
Crash on server startup with version 2.0.2-68

### ISSUE THREAD

**Issue by BakermanLP** [joshiejack/Enchiridion#49]
Hello,
I am trying to upgrade my modpack and got the following error on a server startup:

[09:24:14] [Server thread/ERROR] [FML/]: Caught exception from Enchiridion
java.lang.NoClassDefFoundError: joshie/enchiridion/helpers/ClientHelper
        at joshie.enchiridion.designer.BookRegistry.getData(BookRegistry.java:238) ~[BookRegistry.class:?]
        at joshie.enchiridion.designer.BookRegistry.getData(BookRegistry.java:234) ~[BookRegistry.class:?]
        at joshie.enchiridion.designer.ItemBook.func_77653_i(ItemBook.java:30) ~[ItemBook.class:?]
        at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
        at enchiridion.BookBinderHelper.registerBook(BookBinderHelper.java:56) ~[BookBinderHelper.class:?]
        at enchiridion.BookBinderHelper.registerBooks(BookBinderHelper.java:95) ~[BookBinderHelper.class:?]
        at enchiridion.Enchiridion.init(Enchiridion.java:66) ~[Enchiridion.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.
10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.
10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:713) [Loader.class:?]
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: joshie.enchiridion.helpers.ClientHelper
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
        ... 38 more
Caused by: java.lang.RuntimeException: Attempted to load class joshie/enchiridion/helpers/ClientHelper for invalid side SERVER
        at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50) ~[forge-1.7.10-10.13.3.1403-1.7.10-univ
ersal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
        ... 38 more

More information about the modpack can be found here: https://github.com/BakermanLP/ProjectPhoenix

There are all version information an changed config files.

Thanks for reading.

Michael (aka BakermanLP)

**Comment by joshiejack** [comment]
2.0.2 is still in dev so I haven't done any server testing yet. But thanks for reporting.

**Comment by BakermanLP** [comment]
That's why i am doing this :-)
