### ISSUE TITLE
Client Crash with version 2.0.1-65

### ISSUE THREAD

**Issue by BakermanLP** [joshiejack/Enchiridion#50]
Here is a part of the crash report. That happend on opening the creative inventory and clicking on the search icon. In my inventory is the Botania book and a book binder with several books.

Description: Updating screen events

java.lang.NullPointerException: Updating screen events
        at joshie.enchiridion.designer.ItemBook.getDisplayName(ItemBook.java:36)
        at joshie.enchiridion.designer.ItemBook.func_77653_i(ItemBook.java:32)
        at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
        at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:489)
        at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378)
        at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:350)
        at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
        at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
        at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
        at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
        at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
        at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
        at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
        at org.multimc.EntryPoint.listen(EntryPoint.java:165)
        at org.multimc.EntryPoint.main(EntryPoint.java:54)

Thanks for reading

Michael (aka BakermanLP)

**Comment by GirafiStudios** [comment]
Can't reproduce in Enchiridion 2.0.2a
